### PR TITLE
#245 Add clearMemoryCache and cookie jar support

### PR DESCRIPTION
**Pull request by mjgp2**

### CODE REVIEW

**Comment by amir20** [comment]
This has problems all over. cookie jar needs to be added to `package.json` and please add tests.

**Comment by mjgp2** [comment]
Cookie jar is part of phantom 2.x.

I was more looking at whether or not you think the cookie API makes sense? Sorry, should have added comment to the PR.

I'm using this branch currently, when you're on phantom 2.x I'll loop back around this and add the tests if we agree the cookie API.

**Comment by amir20** [comment]
That makes more sense. We don't use phantom 2 on travis. I am not sure if we should. It fails on travis because it can't find it.

**Comment by JohnyDays** [comment]
I needed this, and am using this pull request right now. Everything seems to be working :+1:

**Pull request closed without merging**
