### PR TITLE
Fix issue #230.

### PR DESCRIPTION
**Pull request by bradleyayers**

### CODE REVIEW

**Comment by bradleyayers** [comment]
This also fixes #185.

**Comment by bradleyayers** [comment]
Actually I see in the docs now that the recommended API is using `page.set('onAlert', …)`, so probably don't want to take the API in this direction?

**Comment by amir20** [comment]
You didn't compile `page.js`. However, I do think that I favor `page.set(...)` I just don't know if it works because I have never tried it. If it works, let's close this.

**Comment by amir20** [comment]
After going through old tickets. I believe `page.set()` does work.

**Pull request closed without merging**
