### PR TITLE
Update browserify and related dependencies (tests on io.js)

### PR DESCRIPTION
**Pull request by anko**
Patch version bump maybe.

The browserify major version going from 1 to 10 sounded worrying, but went without a hitch, other than that CoffeeScript support has moved to a separate transform plugin.

- - -

I put the changes to the big compiled JS files in a separate commit for clarity. (Why are those in git, by the way?)

### CODE REVIEW

**Comment by amir20** [comment]
Can you update the coffee files and compile to js instead? We need to checkin the js files because some people use javascript npm without needing to compile coffee scripts.

**Comment by anko** [comment]
The second commit e7404fc contains the updated JS. Sorry if that was unclear.

A prepublish script in `package.json` [along these lines](https://github.com/anko/tests-ex-markdown/blob/master/package.json#L7) would cause the coffee to be compiled automatically on `npm publish` so only JS is present in the npm package that users download. [More info here.](https://docs.npmjs.com/misc/scripts)

**Comment by amir20** [comment]
It's unclear because you didn't make the changes to CoffeeScript. I prefer the coffee script be the "real source code" where it compiles to JS. 

I like trying to use the `script` field to precompile everything. Could you make this change?

**Comment by amir20** [comment]
Wait, I think I misunderstood this pull request. You didn't actually make any changes to the CoffeeScript. This was due to updating the compiler. 

This makes sense now.

**Comment by amir20** [comment]
Given that test cases pass. I am merging. I'll create an issue for using `script`

**Pull request merged**
